### ISSUE TITLE
frontend panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by HarrisKuo** [nebulaim/telegramd#11]
I0129 15:02:58.032560   17120 handler.go:78] setOnline - SetOnline: {user_id:1 auth_key_id:-2111844437713713368 session_id:8944203041230752133 server_id:1 netlib_session_id:20 }
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13cf27f]

goroutine 175 [running]:
github.com/nebulaim/telegramd/mtproto.(*TLContactsBlocked).GetBlocked(...)
	/Users/user/GoPath/src/github.com/nebulaim/telegramd/mtproto/codec_schema.tl.pb.go:4573
github.com/nebulaim/telegramd/mtproto.(*TLContactsBlocked).Encode(0xc420503b38, 0xc420020670, 0xc420020600, 0x0)
	/Users/user/GoPath/src/github.com/nebulaim/telegramd/mtproto/codec_schema.tl.pb.go:4587 +0x17f
github.com/nebulaim/telegramd/mtproto.(*Contacts_Blocked).Encode(0xc420274a70, 0x0, 0x200, 0xc42042e400)
	/Users/user/GoPath/src/github.com/nebulaim/telegramd/mtproto/codec_schema.tl.pb.go:4521 +0x131
github.com/nebulaim/telegramd/mtproto.(*TLRpcResult).Encode(0xc42014f1a0, 0x69, 0x70, 0x69)
	/Users/user/GoPath/src/github.com/nebulaim/telegramd/mtproto/parsed_manually_types.go:189 +0x16c
github.com/nebulaim/telegramd/mtproto.(*EncryptedMessage2).encode(0xc42032cb40, 0xe2b138ac45308728, 0xc420068700, 0x100, 0x100, 0xc420289140, 0x0, 0xc4202890e0, 0xc420503f60, 0xc42001c338)
	/Users/user/GoPath/src/github.com/nebulaim/telegramd/mtproto/message.go:143 +0x4c
github.com/nebulaim/telegramd/mtproto.(*MTProtoCodec).Send(0xc4202c0230, 0x19015a0, 0xc42032cb40, 0x0, 0x0)
	/Users/user/GoPath/src/github.com/nebulaim/telegramd/mtproto/codec.go:234 +0x822
github.com/nebulaim/telegramd/net.(*Session).sendLoop(0xc42029c080)
	/Users/user/GoPath/src/github.com/nebulaim/telegramd/net/session.go:121 +0x167
created by github.com/nebulaim/telegramd/net.newSession
	/Users/user/GoPath/src/github.com/nebulaim/telegramd/net/session.go:61 +0x139

**Comment by wubenqi** [comment]
fixed! 
thanks
