### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by yumcoder-platform** [nebulaim/telegramd#13]
to install the server the following components are required:
-- Mysql
-- Redis
-- Golang 1.10
-- change the config file for connection string of Mysql and Redis if needed

is the list are correct and complete?

in installation process I get the following error, I would be obliged if you could help me about it.
```
mkdir $GOPATH/src/github.com/nebulaim/
cd $GOPATH/src/github.com/nebulaim/
git clone https://github.com/nebulaim/telegramd.git
cd $GOPATH/src/github.com/nebulaim/telegramd/access/frontend
go get
go build
cd $GOPATH/src/github.com/nebulaim/telegramd/access/session
go get
go build
cd $GOPATH/src/github.com/nebulaim/telegramd/push/sync
go get
go build
cd $GOPATH/src/github.com/nebulaim/telegramd/biz_server
go get
go build
cd $GOPATH/src/github.com/nebulaim/telegramd/access/frontend
./frontend
```
![image](https://user-images.githubusercontent.com/29568969/38167494-dc12cc08-354a-11e8-949f-f3e14933ce92.png)

and when 
```
cd $GOPATH/src/github.com/nebulaim/telegramd/access/session
./session
```

![image](https://user-images.githubusercontent.com/29568969/38167389-91b64014-3549-11e8-9c97-2b869e65f25b.png)

**Comment by wubenqi** [comment]
please paste full log.
thanks

**Comment by yumcoder-platform** [comment]
```
GOROOT=/home/omid/dev/go-sdk #gosetup
GOPATH=/home/omid/dev/workspaces/Yumcoder/Yumcoder-Server:/home/omid/dev/workspaces/go #gosetup
/home/omid/dev/go-sdk/bin/go build -i -o /tmp/___go_build_session_go /home/omid/dev/workspaces/Yumcoder/Yumcoder-Server/src/github.com/nebulaim/telegramd/access/session/session.go #gosetup
/tmp/___go_build_session_go #gosetup
I0401 08:47:23.335207    4287 base.go:60] RegisterPtotocol: mtproto
I0401 08:47:23.336693    4287 base.go:60] RegisterPtotocol: zproto
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x17f9340, 0xf6af91, 0xf, 0x10d6e60, 0xfac358)
	/home/omid/dev/go-sdk/src/net/http/server.go:2353 +0x239
net/http.(*ServeMux).HandleFunc(0x17f9340, 0xf6af91, 0xf, 0xfac358)
	/home/omid/dev/go-sdk/src/net/http/server.go:2368 +0x55
net/http.HandleFunc(0xf6af91, 0xf, 0xfac358)
	/home/omid/dev/go-sdk/src/net/http/server.go:2380 +0x4b
github.com/coreos/etcd/vendor/golang.org/x/net/trace.init.0()
	/home/omid/dev/workspaces/Yumcoder/Yumcoder-Server/src/github.com/coreos/etcd/vendor/golang.org/x/net/trace/trace.go:115 +0x42

Process finished with exit code 2
```

**Comment by yumcoder-platform** [comment]
base on the https://github.com/grpc/grpc-go/issues/566 I guess the problem is related to import section because:

![image](https://user-images.githubusercontent.com/29568969/38169958-cee699a4-358d-11e8-8e30-346b1e85bd8a.png)

"github.com/nebulaim/telegramd/base/base"   ---- must be changed to ---->  "github.com/nebulaim/telegramd/baselib/base"
 also ...

![image](https://user-images.githubusercontent.com/29568969/38169967-1e2964d8-358e-11e8-9366-22cf0bbc7dfc.png)

![image](https://user-images.githubusercontent.com/29568969/38169969-379a6f52-358e-11e8-97e3-ce4821aa0aad.png)


![image](https://user-images.githubusercontent.com/29568969/38169975-5ad3006a-358e-11e8-8b60-f2434c024b69.png)


![image](https://user-images.githubusercontent.com/29568969/38169980-6d823bea-358e-11e8-8ffa-6b804ba6cc86.png)

**Comment by wubenqi** [comment]
thanks:)

**Comment by yumcoder-platform** [comment]
the session server error is:

```
I0402 08:20:23.000731    6142 base.go:60] RegisterPtotocol: mtproto
I0402 08:20:23.002630    6142 base.go:60] RegisterPtotocol: zproto
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x17fa540, 0xf6de38, 0xf, 0x10d9e80, 0xfaf2a0)
	/home/omid/dev/go-sdk/src/net/http/server.go:2353 +0x239
net/http.(*ServeMux).HandleFunc(0x17fa540, 0xf6de38, 0xf, 0xfaf2a0)
	/home/omid/dev/go-sdk/src/net/http/server.go:2368 +0x55
net/http.HandleFunc(0xf6de38, 0xf, 0xfaf2a0)
	/home/omid/dev/go-sdk/src/net/http/server.go:2380 +0x4b
github.com/coreos/etcd/vendor/golang.org/x/net/trace.init.0()
	/home/omid/dev/telegram/telegramd-master/src/github.com/coreos/etcd/vendor/golang.org/x/net/trace/trace.go:115 +0x42

Process finished with exit code 2
```

have you any suggestions or idea?

**Comment by yumcoder-platform** [comment]
my problem is resolved by deleting the **vendor** folder in the following folder:

![image](https://user-images.githubusercontent.com/29568969/38182862-81c7fc70-3651-11e8-8beb-15afc8b0cd51.png)

:)
