### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by yumcoder-platform** [nebulaim/telegramd#18]
- protolRegisters -> **ProtocolRegisters**

https://github.com/nebulaim/telegramd/blob/555b6b1f0f50811adf6053c0b7b76ae84f1d2e3b/baselib/net2/base.go#L56

- RegisterPtotocol -> **RegisterProtocol**

https://github.com/nebulaim/telegramd/blob/555b6b1f0f50811adf6053c0b7b76ae84f1d2e3b/baselib/net2/base.go#L59

**Comment by wubenqi** [comment]
fixed, thanks.
