### ISSUE TITLE
todo -mysql_client

### ISSUE THREAD

**Issue by yumcoder-platform** [nebulaim/telegramd#22]
what are checks do you mean?

https://github.com/nebulaim/telegramd/blob/04f8684f7b621e0d650e858cfd19fb19b182deb8/baselib/mysql_client/mysql_client_manager.go#L42

**Comment by wubenqi** [comment]
Config.Name non empty check, or a configuration file leads to multiple instances of the same config.Name

**Comment by yumcoder-platform** [comment]
I will do it

**Comment by yumcoder-platform** [comment]
if config.Name != "" {
			err := fmt.Errorf("InstallModelManager - config error: config.Name is empty")
			panic(err)
		}
		if val, ok := mysqlClients.mysqlClients[config.Name]; ok {
			err := fmt.Errorf("InstallModelManager - config error: dublicated config.Name {%v}", val)
			panic(err)
		}
