### ISSUE TITLE
 not find userId by authKeyId

### ISSUE THREAD

**Issue by aliakbari** [nebulaim/telegramd#23]
hi
i cloned https://github.com/DrKLO/Telegram/tree/9e4f5491f446b781eb5eee951a4f0c2cacc1cf7e
and set app_id =1 and APP_HASH="8d5279c58cxdcbd0822bab01cb514bc2"
and build project.
but when start app get error in session socket

I0412 17:14:58.873430   44523 session.go:284] authUserId: 0, sessDatas: &{15 0 0xc4200a9730 5577006791947779410 6976559752811022898 [0xc420474100 0xc420474140 0xc4204741a0 0xc420474200]}
E0412 17:14:58.874254   44523 session_util.go:81] not find userId by authKeyId: -142496445277948921
I0412 17:14:58.875085   44523 session_client.go:194] onNewSessionCreated - request data: api_id:37813 device_model:"samsungSM-N920C" system_version:"SDK 24" app_version:"4.2.1 (10431)" system_lang_code:"en-US" lang_pack:"android" lang_code:"en" query:"}\325\017\200"
I0412 17:14:58.875212   44523 session_client.go:315] onInitConnection - request: api_id:37813 device_model:"samsungSM-N920C" system_version:"SDK 24" app_version:"4.2.1 (10431)" system_lang_code:"en-US" lang_pack:"android" lang_code:"en" query:"}\325\017\200"
E0412 17:14:58.875592   44523 session_util.go:81] not find userId by authKeyId: -142496445277948921
I0412 17:14:58.875664   44523 session_client.go:329] onRpcRequest - request: {}
I0412 17:14:58.875745   44523 rpc_client.go:109] Invoke - method: {/mtproto.RPCLangpack/langpack_getLanguages}, req: {}
I0412 17:14:58.875806   44523 rpc_client.go:111] Invoke - NewReplyFunc: {}, t: {*mtproto.Vector_LangPackLanguage}
I0412 17:14:58.876091   44523 rpc_client.go:118] Invoke - NewReplyFunc: {}

please help me

**Comment by aliakbari** [comment]
I know, but why not create the system itself?
Why not document the client side settings?

**Comment by wubenqi** [comment]
It might be a bug,
I'll check it.

**Comment by wubenqi** [comment]
client side settings, see
https://github.com/nebulaim/telegramd/issues/15

**Comment by wubenqi** [comment]
Sorry， now telegramd is still in the development state, many functions are not stable. After the release of the 0.1 version, we will issue the client side settings.

**Comment by aliakbari** [comment]
why etcd not start when start session process?
what is your golang version? is it important?
i understand in  development but i love start it and change it. please help to start service.

**Comment by wubenqi** [comment]
etcd Version: 3.2.12
Go Version: go1.9.2
Go OS/Arch: darwin/amd64
