### ISSUE TITLE
TL expression meaning?

### ISSUE THREAD

**Issue by yumcoder-platform** [nebulaim/telegramd#30]
can you help me to understand the following TL expression?

```inputMediaPhotoExternal#922aec1 flags:# url:string caption:string ttl_seconds:flags.0?int = InputMedia;```

- inputMediaPhotoExternal (combinator name)------> is constructor of TYPE InputMedia
- 922aec1 (combinator identifier) ---------is crc32 of the following string--------> ```inputMediaPhotoExternal flags:# url:string caption:string ttl_seconds:flags.0?int = InputMedia```

1. can you describe me to understand **#** and **flags.0**
```
TYPE InputMedia{
 flags:#       >>>>> what does mean?
 url:string 
 caption:string 
 ttl_seconds:flags.0?int   >>>>> what does mean?
}
```

2. <%Message>   >>>>> what does mean?
messages:vector<%Message> = MessageContainer;

3. ?  >>>>> what does mean?
int ? = Int;

4. 4*[ int ] >>>>> what does mean?
int128 4*[ int ] = Int128;

5.  {t:Type} # [ t ]    >>>>> what does mean?
vector {t:Type} # [ t ] = Vector t;

**Comment by wubenqi** [comment]
1. can you describe me to understand # and flags.0
 >> Flags# can be understood as the optional field of Google protobuf2
2. 3. 4. 5.
 >> I do't known. :(

**Comment by wubenqi** [comment]
https://core.telegram.org/mtproto/TL

**Comment by yumcoder-platform** [comment]
thanks.

**Comment by yumcoder-platform** [comment]
? >>>>>    There are also “pseudo-declarations” that are allowed only to declare built-in types
int ? = Int;

https://core.telegram.org/mtproto/TL-formal#combinator-declarations

**Comment by yumcoder-platform** [comment]
{t:Type} # [ t ] >>>>>  

```{t:Type}```     is optinal field
```#```  or nat     a positive a real constant (> 0)
```[ t ]```            s sequeace of # data of type t

vector {t:Type} # [ t ] = Vector t;

**Comment by yumcoder-platform** [comment]
can you describe me to understand # and flags.0
```TYPE InputMedia{
 flags:#       >>>>>  flag is a field with positive number type
 url:string 
 caption:string 
 ttl_seconds:flags.0?int   >>>>> this filed exist and the type is int if bit 0 of flag is set
}
```
when we read the flags: # field, if we want to know if the flag ttl_seconds:flags.0?int is set or not we must test the bit 0 inside the flag

**Comment by wubenqi** [comment]
yes
