### ISSUE TITLE
first release date?

### ISSUE THREAD

**Issue by aliakbari** [nebulaim/telegramd#35]
What functionality have been developed in the program so far and you think the first release will be published?
For example, why the contact list does not sync?

**Comment by wubenqi** [comment]
**For example, why the contact list does not sync?**
> Can you describe the details of the problem?

**Comment by aliakbari** [comment]
After login i cant chat with others and contact table is empty. 
Whick functionalties of telegram developed by you and when first release?

**Comment by wubenqi** [comment]
You can register several more accounts so you can see the contacts.
