### ISSUE TITLE
TcpClientGroupManager vs TcpClient

### ISSUE THREAD

**Issue by yumcoder-platform** [nebulaim/telegramd#46]
why is TcpClientGroupManager used insteed of TcpClient when only a cilent is set ```clients := map[string][]string{
		"session": []string{"127.0.0.1:10000"},
	} ```
https://github.com/nebulaim/telegramd/blob/8dd723faf67d39b02d8e934642ec48afb1bd2205/access/frontend/server/server.go#L187

**Comment by wubenqi** [comment]
At the end of the deployment, frontend can connect a lot of session_server.
At present, the main task is to improve functions and improve distributed support in the future.
