### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by ghost** [nebulaim/telegramd#5]
There are no build notes.

**Comment by cppfuns** [comment]
是否方便建个聊天群，持续关注您，期待有一个好用的telegram server

**Comment by CitoplasmaX** [comment]
I don't understand Chinese.

**Comment by wubenqi** [comment]
@CitoplasmaX google translate:)

**Comment by CitoplasmaX** [comment]
Jajajajaja, you are right but google translate it is not perfect.

**Comment by CitoplasmaX** [comment]
I comment about compiling the source code of the server and using it for my own instance of "Telegram" (in quotes because it is not official).

I can not find instructions for this task.

**Comment by wubenqi** [comment]
sorry， there are still some problems not yet solved, but also wait for some time.

**Comment by CitoplasmaX** [comment]
No problem, i will wait some time.

**Comment by yumcoder-platform** [comment]
I guess it is the time to resolved/close the issue, see issues #15 and #67
