### ISSUE TITLE
not find userId by authKeyId: 8708834458289943132

### ISSUE THREAD

**Issue by aliakbari** [nebulaim/telegramd#53]
I0429 17:36:39.985667   16438 session.go:286] authUserId: 0, sessDatas: &{824 0 0xc42026f2d0 5577006791947779410 -6232217774971801190 0 [0xc420201940 0xc420201a60]}
E0429 17:36:39.986417   16438 session_util.go:91] not find userId by authKeyId: 8708834458289943132
I0429 17:36:39.986652   16438 session_client.go:272] onGetFutureSalts - request data: num:32
E0429 17:36:39.987225   16438 session_util.go:91] not find userId by authKeyId: 8708834458289943132
I0429 17:36:39.987467   16438 session_client.go:318] onMsgsAck - request: data2:<msg_ids:6549856046752427497 msg_ids:6549856046752465081 >
I0429 17:36:39.987799   16438 server.go:139] recv peer(127.0.0.1:37628) data: {&{824 1 0xc42026f5e0 0xc420201cc0}}
I0429 17:36:39.988273   16438 decode.go:319] NewTLObjectByClassID, classID: 62d6b459
I0429 17:36:39.988484   16438 session.go:179] processOthers - request data: data2:<msg_ids:6549856046754584241 >
I0429 17:36:39.988743   16438 session.go:82] newSessionDataList - sessDatas: &{824 0 0xc42026f5e0 5577006791947779410 -6232217774971801190 0 [0xc420201d40]}
I0429 17:36:39.988959   16438 session.go:286] authUserId: 0, sessDatas: &{824 0 0xc42026f5e0 5577006791947779410 -6232217774971801190 0 [0xc420201d40]}
E0429 17:36:39.989519   16438 session_util.go:91] not find userId by authKeyId: 8708834458289943132
I0429 17:36:39.989777   16438 session_client.go:318] onMsgsAck - request: data2:<msg_ids:6549856046754584241 >
I0429 17:36:40.049193   16438 server.go:139] recv peer(127.0.0.1:37628) data: {&{824 1 0xc42026f730 0xc4202ba020}}
I0429 17:36:40.049326   16438 decode.go:319] NewTLObjectByClassID, classID: 62d6b459
I0429 17:36:40.049397   16438 session.go:179] processOthers - request data: data2:<msg_ids:6549856046857287265 >
I0429 17:36:40.049486   16438 session.go:82] newSessionDataList - sessDatas: &{824 0 0xc42026f730 5577006791947779410 -6232217774971801190 0 [0xc4202ba0c0]}
I0429 17:36:40.049553   16438 session.go:286] authUserId: 0, sessDatas: &{824 0 0xc42026f730 5577006791947779410 -6232217774971801190 0 [0xc4202ba0c0]}
E0429 17:36:40.050410   16438 session_util.go:91] not find userId by authKeyId: 8708834458289943132
I0429 17:36:40.051001   16438 session_client.go:318] onMsgsAck - request: data2:<msg_ids:6549856046857287265 >
I0429 17:36:48.522088   16438 server.go:139] recv peer(127.0.0.1:37628) data: {&{824 1 0xc42026f880 0xc4202ba320}}
I0429 17:36:48.522149   16438 decode.go:319] NewTLObjectByClassID, classID: b921bd04
I0429 17:36:48.522162   16438 session.go:179] processOthers - request data: num:32
I0429 17:36:48.522188   16438 session.go:82] newSessionDataList - sessDatas: &{824 0 0xc42026f880 5577006791947779410 -6232217774971801190 0 [0xc4202ba3e0]}
I0429 17:36:48.522201   16438 session.go:286] authUserId: 0, sessDatas: &{824 0 0xc42026f880 5577006791947779410 -6232217774971801190 0 [0xc4202ba3e0]}
E0429 17:36:48.522979   16438 session_util.go:91] not find userId by authKeyId: 8708834458289943132
I0429 17:36:48.522994   16438 session_client.go:272] onGetFutureSalts - request data: num:32
I0429 17:36:48.580408   16438 server.go:139] recv peer(127.0.0.1:37628) data: {&{824 1 0xc42026f9d0 0xc4202ba4a0}}
I0429 17:36:48.580534   16438 decode.go:319] NewTLObjectByClassID, classID: 62d6b459
I0429 17:36:48.580606   16438 session.go:179] processOthers - request data: data2:<msg_ids:6549856085047304245 >
I0429 17:36:48.580700   16438 session.go:82] newSessionDataList - sessDatas: &{824 0 0xc42026f9d0 5577006791947779410 -6232217774971801190 0 [0xc4202ba7a0]}
I0429 17:36:48.580784   16438 session.go:286] authUserId: 0, sessDatas: &{824 0 0xc42026f9d0 5577006791947779410 -6232217774971801190 0 [0xc4202ba7a0]}
E0429 17:36:48.581302   16438 session_util.go:91] not find userId by authKeyId: 8708834458289943132
I0429 17:36:48.581402   16438 session_client.go:318] onMsgsAck - request: data2:<msg_ids:6549856085047304245 >

**Comment by wubenqi** [comment]
fixed.
