### ISSUE TITLE
frontend gen seqNum todo

### ISSUE THREAD

**Issue by yumcoder-platform** [nebulaim/telegramd#62]
SeqNum can be generated by NextId() -- in id.go ?

https://github.com/nebulaim/telegramd/blob/ea712b6bf22d3d42aed183dcb5269371c05b2ee5/access/frontend/server/server.go#L437

**Comment by wubenqi** [comment]
Using an increasing sequence number.

**Comment by yumcoder-platform** [comment]
the following implementation is good for such situation
 or  
NextId() in id.go is better?

import "sync/atomic"

var ops uint64
atomic.AddUint64(&ops, 1)
atomic.LoadUint64(&ops)
