### ISSUE TITLE
test functionality through chat by another contact

### ISSUE THREAD

**Issue by yumcoder-platform** [nebulaim/telegramd#64]
how to create anther contact and test implemented functionality?
or
I would thankful if you share a scenario in order to test development functionality

**Comment by wubenqi** [comment]
1. regist contact
2. setting contact's username
3. search contact by username

**Comment by yumcoder-platform** [comment]
regist contact   ------------> do it by add manually in user table in mysql or add in android client?
    setting contact's username  ------------> do it in android client?
    search contact by username ------------> do it in android client?
