### ISSUE TITLE
data-base

### ISSUE THREAD

**Issue by yumcoder-platform** [nebulaim/telegramd#76]
database is critical component in high read/write app and by considering messaging app I guess there are 4 data-base candidates:
-- Mysql
-- Postgres
-- Mongodb
-- Cassandra

I think 3 criteria are importance:
-- performance 
-- clustering
-- sharding/portioning

also I think, in such situation TCP tuning in OS is important.
I would be obliged if you cloud kindly share your opinion about best choice for data-base component. 
-- what are reasons behind selecting the Mysql for the telegramd. 
-- there is a benchmark for it
-- success story for Mysql in messenger or similar app

**Comment by wubenqi** [comment]
1. I am more familiar with MySQL
2. MySQL's ecosystem is very mature, operation and maintenance is also convenient, there are many third party mature middleware.
3. starting phase with MySQL, the project is more controllable
4. also has a larger Messenger Using MySQL

**Comment by yumcoder-platform** [comment]
vary thanks. also I guess the project design is good and simply adapter to other data-base can be written in future.
can you share an example for 4.

**Comment by wubenqi** [comment]
also I guess the project design is good and simply adapter to other data-base can be written in future.
> yes.

can you share an example for 4.
> https://www.dingtalk.com/
