### ISSUE TITLE
Wrong codepage

### ISSUE THREAD

**Issue by recoilme** [nebulaim/telegramd#84]
Hello
1. Telegram use utf16 internally, you must encode it to utf8 (for parsing). You find it when/if start working with entities
2. Mysql/mariadb use wrong utf8 (3 bytes), you must use utf8mb4 (4 bytes). You find it then start working with emoji/stickers. Some emoji 4 byte length

Example from tggram.com:
Connection:
```
func InitDb(dbName string) {
	db, err := sql.Open("mysql", "recoilme:@/"+dbName+"?charset=utf8mb4,utf8")
	defer db.Close()
	if err != nil || db == nil {
		panic(err)
	}
	db.SetConnMaxLifetime(time.Second * 5)
	db.SetMaxIdleConns(0)
	db.SetMaxOpenConns(5)
	var createTableStatements = []string{
		//CREATE DATABASE IF NOT EXISTS blog CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;;
		`SET NAMES 'utf8mb4'`,
		`SET CHARACTER SET utf8mb4`,
		`CREATE TABLE IF NOT EXISTS chat (
			id VARCHAR(100) NOT NULL,
			data TEXT NULL,
			meta TEXT NULL,
			created TIMESTAMP DEFAULT now(), 
			updated TIMESTAMP DEFAULT now() ON UPDATE now(),			
			PRIMARY KEY (id)
		)`,
	}
	for _, stmt := range createTableStatements {
		_, err := db.Exec(stmt)
		if err != nil {
			panic(err)
		}
	}
	err = db.Ping()
	if err != nil {
		panic(err.Error()) // proper error handling instead of panic in your app
	}
}
```

Decode utf16:
```
func extructEntity(runes []rune, offset int, length int) (result string) {

	utf16Runes := utf16.Encode(runes)
	len := len(utf16Runes)

	if offset > len || offset+length > len {
		return
	}
	var substr string
	if length > 0 {

		substr = string(utf16.Decode(utf16Runes[offset:(offset + length)]))
	} else {
		substr = string(utf16.Decode(utf16Runes[offset:]))
	}
	result = strings.Replace(substr, "<", "&lt", -1)
	result = strings.Replace(result, ">", "&gt;", -1)
	return result
}
```

Links:
https://mathiasbynens.be/notes/mysql-utf8mb4
https://stackoverflow.com/questions/49035310/php-telegram-bot-extract-url-in-utf-16-code-units

**Comment by wubenqi** [comment]
thanks.

1. the telegramd database access has been configured with utf8mbcs. Please refer to the configuration file. For example:
```
biz_server/biz_server.toml
[[mysql]]
name = "immaster"
dsn = "root:@/nebulaim?charset=utf8mb4"
```
2. the nebulaim database table messages.message_data has also been set to utf8mb4_general_ci.
3. for the telegram server, we can not care about whether or not to use utf16. We only need to receive the client data, store it and forward it to the client.

**Comment by wubenqi** [comment]
sorry!

I found that the name of telegram can also set the emoji/stickers, uh, you're right,  database should be set to utf8mb4.

**Comment by recoilme** [comment]
I found utf8 here to https://github.com/nebulaim/telegramd/blob/master/scripts/nebulaim.sql

**Comment by wubenqi** [comment]
thanks.
I'll fix it.
