### ISSUE TITLE
device register error

### ISSUE THREAD

**Issue by aliakbari** [nebulaim/telegramd#86]
I0605 22:50:53.841621   28845 account.registerDevice_handler.go:33] account.registerDevice#637ea878 - metadata: {"server_id":1,"netlib_session_id":2,"auth_id":-5664057375626680553,"session_id":7419619926324524429,"span_id":1004065539208908800,"receive_time":1528222853,"user_id":1,"client_msg_id":6563667178556121092,"layer":73}, request: {"token_type":2,"token":"cbb4jPR3udk:APA91bH9ByvtAnYBv_7As7Fpsqvn7vn1z2-T1dHeO2CQZMesmYTz1RcPhtAKc80Yjwn7z4Eh1Rvt9nSyKoWL91GvFNBtQXp99rhlPev52OQeX2-l_OhsAp15f2jVksPBCOebxOs17PRL"}
E0605 22:50:53.843100   28845 devices_dao.go:43] NamedExec in Insert(&{0 -5664057375626680553 1 2 cbb4jPR3udk:APA91bH9ByvtAnYBv_7As7Fpsqvn7vn1z2-T1dHeO2CQZMesmYTz1RcPhtAKc80Yjwn7z4Eh1Rvt9nSyKoWL91GvFNBtQXp99rhlPev52OQeX2-l_OhsAp15f2jVksPBCOebxOs17PRL 0  }), error: Error 1406: Data too long for column 'token' at row 1
E0605 22:50:53.843256   28845 rpc_recovery_handler.go:32] BizUnaryRecoveryHandler - goroutine 91 [running]:
runtime/debug.Stack(0xc420907aa0, 0x7f43fab78e40, 0x0)
 /opt/go/src/runtime/debug/stack.go:24 +0xa7
github.com/nebulaim/telegramd/baselib/grpc_util.BizUnaryRecoveryHandler(0x1a82de0, 0xc4205ee1b0, 0x1109500, 0xc42000e2f8, 0x1173177, 0x4c1557)
 /root/go/src/github.com/nebulaim/telegramd/baselib/grpc_util/rpc_recovery_handler.go:32 +0x34
github.com/nebulaim/telegramd/baselib/grpc_util/middleware/recovery2.unaryRecoverFrom(0x1a82de0, 0xc4205ee1b0, 0x1109500, 0xc42000e2f8, 0x11c8cd0, 0xc4205775d0, 0x4f294a)
 /root/go/src/github.com/nebulaim/telegramd/baselib/grpc_util/middleware/recovery2/interceptors.go:75 +0x5a
github.com/nebulaim/telegramd/baselib/grpc_util/middleware/recovery2.UnaryServerInterceptor.func1.1(0xc420577978, 0x1a82de0, 0xc4205ee1b0, 0xc42064c3e0)
 /root/go/src/github.com/nebulaim/telegramd/baselib/grpc_util/middleware/recovery2/interceptors.go:42 +0x77
panic(0x1109500, 0xc42000e2f8)
 /opt/go/src/runtime/panic.go:491 +0x283
github.com/nebulaim/telegramd/biz/dal/dao/mysql_dao.(*DevicesDAO).Insert(0xc42000e0b0, 0xc4205f2320, 0xc4202465a0)
 /root/go/src/github.com/nebulaim/telegramd/biz/dal/dao/mysql_dao/devices_dao.go:44 +0x396
github.com/nebulaim/telegramd/biz/core/account.RegisterDevice(0xb16539d38a572717, 0x200000001, 0xc4202465a0, 0x98, 0x2)
 /root/go/src/github.com/nebulaim/telegramd/biz/core/account/device.go:47 +0x12b
github.com/nebulaim/telegramd/biz_server/account/rpc.(*AccountServiceImpl).AccountRegisterDevice(0x1b31670, 0x1a82de0, 0xc4205ee1b0, 0xc4209078c0, 0x1b31670, 0xc4205778d8, 0x1)
 /root/go/src/github.com/nebulaim/telegramd/biz_server/account/rpc/account.registerDevice_handler.go:50 +0x1fb
github.com/nebulaim/telegramd/mtproto._RPCAccount_AccountRegisterDevice_Handler.func1(0x1a82de0, 0xc4205ee1b0, 0x10a29e0, 0xc4209078c0, 0xc4205ee1b0, 0xc42064c3e0, 0x4126e8, 0x20)
 /root/go/src/github.com/nebulaim/telegramd/mtproto/schema.tl.sync_service.pb.go:8185 +0x89
github.com/nebulaim/telegramd/baselib/grpc_util/middleware/recovery2.UnaryServerInterceptor.func1(0x1a82de0, 0xc4205ee1b0, 0x10a29e0, 0xc4209078c0, 0xc4209078e0, 0xc420907900, 0x0, 0x0, 0x0, 0x0)
 /root/go/src/github.com/nebulaim/telegramd/baselib/grpc_util/middleware/recovery2/interceptors.go:47 +0xd7
github.com/nebulaim/telegramd/mtproto._RPCAccount_AccountRegisterDevice_Handler(0x11520c0, 0x1b31670, 0x1a82de0, 0xc4205ee1b0, 0xc420268070, 0xc420640440, 0x0, 0x0, 0x0, 0x0)
 /root/go/src/github.com/nebulaim/telegramd/mtproto/schema.tl.sync_service.pb.go:8187 +0x16d
google.golang.org/grpc.(*Server).processUnaryRPC(0xc420459200, 0x1a86c80, 0xc4203b3c80, 0xc4202420f0, 0xc420589050, 0x1b06940, 0x0, 0x0, 0x0)
 /root/go/src/google.golang.org/grpc/server.go:969 +0x92d
google.golang.org/grpc.(*Server).handleStream(0xc420459200, 0x1a86c80, 0xc4203b3c80, 0xc4202420f0, 0x0)
 /root/go/src/google.golang.org/grpc/server.go:1194 +0x1528
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4206208b0, 0xc420459200, 0x1a86c80, 0xc4203b3c80, 0xc4202420f0)
 /root/go/src/google.golang.org/grpc/server.go:677 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
 /root/go/src/google.golang.org/grpc/server.go:675 +0xa1
E0605 22:50:53.843426   28845 rpc_recovery_handler.go:44] Panic: rpc error: code = Unknown desc = panic triggered rpc_error: {rpc error: code = 600 desc = DBERR}
^CI0605 22:50:56.924440   28845 rpc_server.go:95] exit...

**Comment by aliakbari** [comment]
**updating... state in android  with this error in server**
E0605 23:27:56.378339   28892 devices_dao.go:43] NamedExec in Insert(&{0 -5664057375626680553 1 2 cbb4jPR3udk:APA91bH9ByvtAnYBv_7As7Fpsqvn7vn1z2-T1dHeO2CQZMesmYTz1RcPhtAKc80Yjwn7z4Eh1Rvt9nSyKoWL91GvFNBtQXp99rhlPev52OQeX2-l_OhsAp15f2jVksPBCOebxOs17PRL 0  }), error: Error 1062: Duplicate entry '2-cbb4jPR3udk:APA91bH9ByvtAnYBv_7As7Fpsqvn7vn1z2-T1dHeO2CQZMesmY' for key 'token_type'
E0605 23:27:56.378503   28892 rpc_recovery_handler.go:32] BizUnaryRecoveryHandler - goroutine 1151 [running]:
runtime/debug.Stack(0xc4205cb320, 0x7fb3ab677968, 0x0)
        /opt/go/src/runtime/debug/stack.go:24 +0xa7
github.com/nebulaim/telegramd/baselib/grpc_util.BizUnaryRecoveryHandler(0x1a82de0, 0xc420534c30, 0x1109500, 0xc42000fa38, 0x1173177, 0x4c1557)
        /root/go/src/github.com/nebulaim/telegramd/baselib/grpc_util/rpc_recovery_handler.go:32 +0x34
github.com/nebulaim/telegramd/baselib/grpc_util/middleware/recovery2.unaryRecoverFrom(0x1a82de0, 0xc420534c30, 0x1109500, 0xc42000fa38, 0x11c8cd0, 0xc42020f5d0, 0x4f294a)
        /root/go/src/github.com/nebulaim/telegramd/baselib/grpc_util/middleware/recovery2/interceptors.go:75 +0x5a
github.com/nebulaim/telegramd/baselib/grpc_util/middleware/recovery2.UnaryServerInterceptor.func1.1(0xc42020f978, 0x1a82de0, 0xc420534c30, 0xc42065f020)
        /root/go/src/github.com/nebulaim/telegramd/baselib/grpc_util/middleware/recovery2/interceptors.go:42 +0x77
panic(0x1109500, 0xc42000fa38)
        /opt/go/src/runtime/panic.go:491 +0x283
github.com/nebulaim/telegramd/biz/dal/dao/mysql_dao.(*DevicesDAO).Insert(0xc42000e0c8, 0xc4200c9ae0, 0xc4206fba40)
        /root/go/src/github.com/nebulaim/telegramd/biz/dal/dao/mysql_dao/devices_dao.go:44 +0x396
github.com/nebulaim/telegramd/biz/core/account.RegisterDevice(0xb16539d38a572717, 0x200000001, 0xc4206fba40, 0x98, 0x2)
        /root/go/src/github.com/nebulaim/telegramd/biz/core/account/device.go:47 +0x12b
github.com/nebulaim/telegramd/biz_server/account/rpc.(*AccountServiceImpl).AccountRegisterDevice(0x1b31670, 0x1a82de0, 0xc420534c30, 0xc4205cb1e0, 0x1b31670, 0xc42020f8d8, 0x1)
        /root/go/src/github.com/nebulaim/telegramd/biz_server/account/rpc/account.registerDevice_handler.go:50 +0x1fb
github.com/nebulaim/telegramd/mtproto._RPCAccount_AccountRegisterDevice_Handler.func1(0x1a82de0, 0xc420534c30, 0x10a29e0, 0xc4205cb1e0, 0xc420534c30, 0xc42065f020, 0x4126e8, 0x20)
        /root/go/src/github.com/nebulaim/telegramd/mtproto/schema.tl.sync_service.pb.go:8185 +0x89
github.com/nebulaim/telegramd/baselib/grpc_util/middleware/recovery2.UnaryServerInterceptor.func1(0x1a82de0, 0xc420534c30, 0x10a29e0, 0xc4205cb1e0, 0xc4205cb200, 0xc4205cb220, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/nebulaim/telegramd/baselib/grpc_util/middleware/recovery2/interceptors.go:47 +0xd7
github.com/nebulaim/telegramd/mtproto._RPCAccount_AccountRegisterDevice_Handler(0x11520c0, 0x1b31670, 0x1a82de0, 0xc420534c30, 0xc4205285b0, 0xc420657430, 0x0, 0x0, 0x3, 0xc42057c5a0)
        /root/go/src/github.com/nebulaim/telegramd/mtproto/schema.tl.sync_service.pb.go:8187 +0x16d
google.golang.org/grpc.(*Server).processUnaryRPC(0xc420451500, 0x1a86c80, 0xc4204e4600, 0xc4208c7590, 0xc420589a40, 0x1b06940, 0x0, 0x0, 0x0)
        /root/go/src/google.golang.org/grpc/server.go:969 +0x92d
google.golang.org/grpc.(*Server).handleStream(0xc420451500, 0x1a86c80, 0xc4204e4600, 0xc4208c7590, 0x0)
        /root/go/src/google.golang.org/grpc/server.go:1194 +0x1528
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4204050c0, 0xc420451500, 0x1a86c80, 0xc4204e4600, 0xc4208c7590)
        /root/go/src/google.golang.org/grpc/server.go:677 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /root/go/src/google.golang.org/grpc/server.go:675 +0xa1
E0605 23:27:56.378808   28892 rpc_recovery_handler.go:44] Panic: rpc error: code = Unknown desc = panic triggered rpc_error: {rpc error: code = 600 desc = DBERR}
I0605 23:28:04.521962   28892 auth.exportAuthorization_handler.go:32] AuthExportAuthorization - metadata: {"server_id":1,"netlib_session_id":2,"auth_id":-5664057375626680553,"session_id":-3445176887585443409,"span_id":1004074895358955520,"receive_time":1528225084,"user_id":1,"client_msg_id":6563676759605955584}, request: {"dc_id":2}

**Comment by wubenqi** [comment]
thanks, I'll fix it and commit.

fix sql,

```
ALTER TABLE `devices` CHANGE `token` `token` VARCHAR(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
```
