### ISSUE TITLE
after video upload NOTRETURN_CLIENT error

### ISSUE THREAD

**Issue by aliakbari** [nebulaim/telegramd#87]
**After downloading the video, the recipient can not receive the video and in server side get NOTRETURN_CLIENT error and other functionalities too with error**

_I0605 23:38:25.853925   29336 messages.readHistory_handler.go:34] messages.readHistory#e306d3a - metadata: {"server_id":1,"netlib_session_id":2,"auth_id":4751556400038306678,"session_id":-7060648465281298913,"span_id":1004077501418442752,"receive_time":1528225705,"user_id":2,"client_msg_id":6563679427072704512}, request: {"peer":{"constructor":2072935910,"data2":{"user_id":1,"access_hash":1004069845391773696}},"max_id":318}
I0605 23:38:25.940167   29336 messages.readHistory_handler.go:94] messages.readHistory#e306d3a - reply: {rpc error: code = 700 desc = NOTRETURN_CLIENT}_

**Comment by wubenqi** [comment]
The get NOTRETURN_CLIENT error problem can be ignored, it means that  messages.readHistory result will return later.

can you upload the video file in telegram group?

**Comment by aliakbari** [comment]
Did you see the video I sent to the group?

**Comment by aliakbari** [comment]
Yes.According to the video I posted, I cant download video or files in recepient user side.
